
apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-node
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: play-node
  template:
    metadata:
      labels:
        app: play-node
    spec:
      containers:
      - image: play-node
        name: play-node
        ports:
        - containerPort: 80